// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POAMs.Web.Data;

#nullable disable

namespace POAMs.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106222445_AddDocumentationReviewFields")]
    partial class AddDocumentationReviewFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("POAMs.Web.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.CCI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCINumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NISTControlId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CCINumber");

                    b.HasIndex("NISTControlId");

                    b.ToTable("CCIs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.ControlDocumentationInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceLocation")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequirementId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewCycleMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("SystemId");

                    b.HasIndex("RequirementId", "SystemId")
                        .IsUnique();

                    b.ToTable("ControlDocumentationInstances");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.ControlDocumentationRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NISTControlId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NISTControlId");

                    b.HasIndex("NISTControlId", "DocType")
                        .IsUnique();

                    b.ToTable("ControlDocumentationRequirements");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Changes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MilestoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("POAMId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("POAMId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.NISTControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControlId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discussion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWithdrawn")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentControlId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedControls")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ControlId")
                        .IsUnique();

                    b.HasIndex("Family");

                    b.ToTable("NISTControls");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.NISTControlAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssessedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssessedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("Implementation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("NISTControlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("POAMId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssessedById");

                    b.HasIndex("AssessedDate");

                    b.HasIndex("POAMId");

                    b.HasIndex("SystemId");

                    b.HasIndex("NISTControlId", "SystemId");

                    b.ToTable("NISTControlAssessments");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.NessusTestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedHosts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedPorts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CVE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CVSSScore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CVSSVector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OriginalScanDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemediationSteps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RescanDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RescanRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RescanResults")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityTestPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TesterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TesterId");

                    b.HasIndex("SecurityTestPlanId", "PluginId");

                    b.ToTable("NessusTestCases");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.POAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OriginalPOAMDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("POCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourcesRequired")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityControl")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaknessOrDeficiency")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemIdentifier");

                    b.HasIndex("POCId");

                    b.HasIndex("SystemId");

                    b.ToTable("POAMs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.STPTestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FixText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RetestRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityTestPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TesterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VulnId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TesterId");

                    b.HasIndex("SecurityTestPlanId", "VulnId");

                    b.ToTable("STPTestCases");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SecurityControlTestCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssessExamine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssessInterview")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AssessTest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentObjective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssessmentObjectiveItems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlEnhancement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Inheritance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InheritedFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonitoringType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverallResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedSTIGIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityTestPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestSteps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SecurityTestPlanId", "ControlId");

                    b.ToTable("SecurityControlTestCases");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SecurityTestPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Assessor2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Assessor2Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizedUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorizingOfficial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ISSMId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LeadAssessorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MACCAL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OSPlatform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("POAMId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrivilegedUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("STIGName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("STIGReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("STIGVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("STPIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ScanDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScanPolicyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScannerVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TestPlanDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestPlanVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TestStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ISSMId");

                    b.HasIndex("LeadAssessorId");

                    b.HasIndex("POAMId");

                    b.HasIndex("STPIdentifier")
                        .IsUnique();

                    b.HasIndex("SystemId");

                    b.ToTable("SecurityTestPlans");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ISSMId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UID")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISSMId");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWindowsAuth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.UserAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("POAMId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("UserId");

                    b.HasIndex("POAMId", "UserId", "AssignmentType")
                        .IsUnique();

                    b.ToTable("UserAssignments");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.AuditLog", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.CCI", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.NISTControl", "NISTControl")
                        .WithMany("CCIs")
                        .HasForeignKey("NISTControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NISTControl");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.ControlDocumentationInstance", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.ControlDocumentationRequirement", "Requirement")
                        .WithMany("Instances")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POAMs.Web.Models.Domain.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Requirement");

                    b.Navigation("ReviewedBy");

                    b.Navigation("System");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.ControlDocumentationRequirement", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.NISTControl", "NISTControl")
                        .WithMany()
                        .HasForeignKey("NISTControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NISTControl");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.Milestone", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "AssignedTo")
                        .WithMany("AssignedMilestones")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.POAM", "POAM")
                        .WithMany("Milestones")
                        .HasForeignKey("POAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("POAM");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.NISTControlAssessment", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "AssessedBy")
                        .WithMany()
                        .HasForeignKey("AssessedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.NISTControl", "NISTControl")
                        .WithMany("Assessments")
                        .HasForeignKey("NISTControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POAMs.Web.Models.Domain.POAM", "POAM")
                        .WithMany()
                        .HasForeignKey("POAMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessedBy");

                    b.Navigation("NISTControl");

                    b.Navigation("POAM");

                    b.Navigation("System");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.NessusTestCase", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.SecurityTestPlan", "SecurityTestPlan")
                        .WithMany("NessusTestCases")
                        .HasForeignKey("SecurityTestPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POAMs.Web.Models.Domain.User", "Tester")
                        .WithMany()
                        .HasForeignKey("TesterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SecurityTestPlan");

                    b.Navigation("Tester");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.POAM", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "POC")
                        .WithMany("POAMsAsPOC")
                        .HasForeignKey("POCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.SystemInfo", "System")
                        .WithMany("POAMs")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("POC");

                    b.Navigation("System");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.STPTestCase", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.SecurityTestPlan", "SecurityTestPlan")
                        .WithMany("TestCases")
                        .HasForeignKey("SecurityTestPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POAMs.Web.Models.Domain.User", "Tester")
                        .WithMany()
                        .HasForeignKey("TesterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SecurityTestPlan");

                    b.Navigation("Tester");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SecurityControlTestCase", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.SecurityTestPlan", "SecurityTestPlan")
                        .WithMany("ControlTestCases")
                        .HasForeignKey("SecurityTestPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityTestPlan");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SecurityTestPlan", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.User", "ISSM")
                        .WithMany()
                        .HasForeignKey("ISSMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.User", "LeadAssessor")
                        .WithMany()
                        .HasForeignKey("LeadAssessorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.POAM", "POAM")
                        .WithMany()
                        .HasForeignKey("POAMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.SystemInfo", "System")
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ISSM");

                    b.Navigation("LeadAssessor");

                    b.Navigation("POAM");

                    b.Navigation("System");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SystemInfo", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "ISSM")
                        .WithMany("ManagedSystems")
                        .HasForeignKey("ISSMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ISSM");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.UserAssignment", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.POAM", "POAM")
                        .WithMany("UserAssignments")
                        .HasForeignKey("POAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POAMs.Web.Models.Domain.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("POAM");

                    b.Navigation("User");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.ControlDocumentationRequirement", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.NISTControl", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("CCIs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.POAM", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SecurityTestPlan", b =>
                {
                    b.Navigation("ControlTestCases");

                    b.Navigation("NessusTestCases");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SystemInfo", b =>
                {
                    b.Navigation("POAMs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.User", b =>
                {
                    b.Navigation("AssignedMilestones");

                    b.Navigation("Assignments");

                    b.Navigation("ManagedSystems");

                    b.Navigation("POAMsAsPOC");
                });
#pragma warning restore 612, 618
        }
    }
}
