// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POAMs.Web.Data;

#nullable disable

namespace POAMs.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106171645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("POAMs.Web.Models.Domain.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Changes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MilestoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("POAMId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("POAMId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.POAM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OriginalPOAMDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("POCId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourcesRequired")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledCompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityControl")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaknessOrDeficiency")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemIdentifier");

                    b.HasIndex("POCId");

                    b.HasIndex("SystemId");

                    b.ToTable("POAMs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ISSMId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ISType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UID")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ISSMId");

                    b.ToTable("Systems");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWindowsAuth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.UserAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("POAMId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedById");

                    b.HasIndex("UserId");

                    b.HasIndex("POAMId", "UserId", "AssignmentType")
                        .IsUnique();

                    b.ToTable("UserAssignments");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.AuditLog", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.Milestone", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "AssignedTo")
                        .WithMany("AssignedMilestones")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.POAM", "POAM")
                        .WithMany("Milestones")
                        .HasForeignKey("POAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("POAM");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.POAM", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "POC")
                        .WithMany("POAMsAsPOC")
                        .HasForeignKey("POCId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.SystemInfo", "System")
                        .WithMany("POAMs")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("POC");

                    b.Navigation("System");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SystemInfo", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "ISSM")
                        .WithMany("ManagedSystems")
                        .HasForeignKey("ISSMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ISSM");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.UserAssignment", b =>
                {
                    b.HasOne("POAMs.Web.Models.Domain.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("POAMs.Web.Models.Domain.POAM", "POAM")
                        .WithMany("UserAssignments")
                        .HasForeignKey("POAMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POAMs.Web.Models.Domain.User", "User")
                        .WithMany("Assignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedBy");

                    b.Navigation("POAM");

                    b.Navigation("User");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.POAM", b =>
                {
                    b.Navigation("Milestones");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.SystemInfo", b =>
                {
                    b.Navigation("POAMs");
                });

            modelBuilder.Entity("POAMs.Web.Models.Domain.User", b =>
                {
                    b.Navigation("AssignedMilestones");

                    b.Navigation("Assignments");

                    b.Navigation("ManagedSystems");

                    b.Navigation("POAMsAsPOC");
                });
#pragma warning restore 612, 618
        }
    }
}
